Apteka/apteka/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #/apteka/
    url(r'^$', views.index, name='index'),
    #/apteka/products
    url(r'^products/$', views.products, name='products'),
    #apteka/products/1
    url(r'^products/(?P<product_id>[0-9]+)/$', views.product_detail, name='product_detail'),
]

Apteka/pharmacy/urls.py
from django.conf.urls import url
from . import views

app_name = 'pharmacy'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^logout/$', views.logout_view, name='logout'),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    url(r'^signin/$', views.SignInView.as_view(), name='sign_in'),

    url(r'^products/$', views.AllProducts.as_view(), name='products'),

    url(r'^products/(?P<pk>[0-9]+)/$', views.ProductDetailView.as_view(), name='product_detail'),

    url(r'^basket/$', views.basket_view, name='basket'),

    url(r'^add_to_basket/$', views.add_to_basket, name='add_to_basket'),

    url(r'^product/add/$', views.CreateProduct.as_view(), name='add_product'),

    url(r'^product/edit/(?P<pk>[0-9]+)/$', views.UpdateProduct.as_view(), name='update_product'),

    url(r'^product/delete/(?P<pk>[0-9]+)/$', views.DeleteProduct.as_view(), name='delete_product'),

    url(r'^pay/$', views.pay_view, name='pay'),

    url(r'^add_pay/$', views.add_pay_view, name='add_pay'),

    url(r'^history/$', views.history_view, name='history'),

    url(r'^history_execution/$', views.history_execution_view, name='history_execution'),

    url(r'^history_status/$', views.history_status_view, name='history_status'),

    url(r'^history_status_change/$', views.history_status_change_view, name='history_status_change'),

    url(r'^sale/$', views.sale_view, name='sale'),
]

Apteka/website/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pharmacy/', include('pharmacy.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apteka/pharmacy/models.py
from django.core.urlresolvers import reverse
from django.core.validators import MinValueValidator
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField(validators=[MinValueValidator(0.0)])
    amount = models.IntegerField(default=0)
    product_logo = models.FileField()
    description = models.TextField(default="", max_length=9999)
    discount = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('pharmacy:product_detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.name


class Basket(models.Model):
    def get_absolute_url(self):
        return reverse('pharmacy:basket', kwargs={'pk':self.pk})

class History(models.Model):
    user = models.CharField(max_length=100)
    order = models.BigIntegerField()
    price = models.FloatField()
    status = models.CharField(max_length=100)
    basket = models.TextField(max_length=9999)

    def get_absolute_url(self):
        return reverse('pharmacy:history', kwargs={'pk':self.pk})

Apteka/pharmacy/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

Apteka/pharmacy/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.models import Group

from .forms import UserForm
from .models import Product
from .models import History
import ast
import hashlib
import time

def get_permissions_to_be_passed_to_template(request):
    return {'has_{}_permission'.format(perm.split('.')[1]): request.user.has_perm(perm)
            for perm in get_all_existing_model_permissions()}


def get_all_existing_model_permissions():
    models = ['product', 'basket']
    for perm in ['add', 'change', 'delete']:
        for model in models:
            yield 'pharmacy.{}_{}'.format(perm, model)


class ProductDetailView(LoginRequiredMixin, generic.DetailView):
    model = Product
    template_name = 'pharmacy/product_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context.update(get_permissions_to_be_passed_to_template(self.request))
        product = context['product']
        product.discount_price = float((100 - int(product.discount)) / 100.0 * float(product.price))
        return context


class AllProducts(LoginRequiredMixin, generic.ListView):
    template_name = 'pharmacy/products.html'
    context_object_name = 'all_products'

    def get_queryset(self):
        products = Product.objects.all()
        for product in products:
            product.discount_price = float((100 - int(product.discount)) / 100.0 * float(product.price))
        return products

    def get_context_data(self, **kwargs):
        context = super(AllProducts, self).get_context_data(**kwargs)
        context.update(get_permissions_to_be_passed_to_template(self.request))
        return context


def index(request):
    if request.user.is_authenticated:
        return render(request, 'pharmacy/index.html', get_permissions_to_be_passed_to_template(request))
    else:
        return render(request, 'pharmacy/index_visitor.html', {})


def get_basket_products(request, selected_product):
    basket_products = {}  # id : basket_product
    basket_product = {}  # id, name, price, amount, url, coupon
    if 'basket_products' in request.COOKIES:
        basket_products = ast.literal_eval(request.COOKIES['basket_products'])

    if selected_product is not None and selected_product.id in basket_products:
        basket_product = basket_products[selected_product.id]
        action = request.POST.get('basket_product_op', '')
        if action == 'minus':
            if basket_product['amount'] == 1:
                del basket_products[selected_product.id]
            elif basket_product['amount'] > 0:
                basket_product['amount'] = basket_product['amount'] - 1
        else:
            basket_product['amount'] = basket_product['amount'] + 1
    elif selected_product is not None:
        basket_product = {'id': selected_product.id, 'name': selected_product.name, 'price': selected_product.price, 'discount': selected_product.discount,
                          'discount_price': float((100 - int(selected_product.discount)) / 100.0 * float(selected_product.price)), 'amount': 1, 'url': selected_product.product_logo.url, 'coupon' : 1.0}
        basket_products[selected_product.id] = basket_product

    return basket_products

def get_basket_price(basket_products):
    price = 0.0
    for basket_product in basket_products.values():
        price = price + (float(basket_product['amount']) * float(basket_product['discount_price']) * float(basket_product['coupon']))

    if price >= 200:
        price = price * 0.85
    elif price >= 100:
        price = price * 0.9
    elif price >= 50:
        price = price * 0.95

    return price

@login_required()
@permission_required('pharmacy.add_basket', 'pharmacy.delete_basket', 'pharmacy.change_basket')
def basket_view(request):
    basket_products = get_basket_products(request, None)
    price = get_basket_price(basket_products)

    context = {'basket_products' : basket_products, 'basket_price' : price}
    permissions = get_permissions_to_be_passed_to_template(request)
    context.update(permissions)

    return render(request, 'pharmacy/basket.html', context)

@login_required()
def add_to_basket(request):
    coupon = request.POST.get('basket_coupon', '')
    if (coupon is not ''):
        basket_products = get_basket_products(request, None)
        discount = 1.0
        if (coupon == 'I WANT 20 DISCOUNT'):
           discount = 0.8
        elif (coupon == 'I WANT 40 DISCOUNT'):
            discount = 0.6
        elif (coupon == 'I WANT 60 DISCOUNT'):
            discount = 0.4
        for basket_product in basket_products.values():
            basket_product['coupon'] = discount
        price = get_basket_price(basket_products)

        context = {'sucess_message': "Updated basket", 'basket_products': basket_products, 'basket_price': price}
        permissions = get_permissions_to_be_passed_to_template(request)
        context.update(permissions)

        response = render(request, 'pharmacy/basket.html', context)
        response.set_cookie('basket_products', basket_products)
        return response
    else:
        try:
            selected_product = get_object_or_404(Product, pk=request.POST['add_to_basket'])
        except (KeyError, ObjectDoesNotExist):

            context = {'error_message': "Cannot add this product to basket"}
            permissions = get_permissions_to_be_passed_to_template(request)
            context.update(permissions)

            return render(request, 'pharmacy/products.html', context)
        else:
            basket_products = get_basket_products(request, selected_product)
            price = get_basket_price(basket_products)

            context = {'sucess_message': "Updated basket", 'basket_products' : basket_products, 'basket_price' : price}
            permissions = get_permissions_to_be_passed_to_template(request)
            context.update(permissions)

            response = render(request, 'pharmacy/basket.html', context)
            response.set_cookie('basket_products', basket_products)
            return response

@login_required()
def pay_view(request):
    basket_products = get_basket_products(request, None)
    price = get_basket_price(basket_products)
    number = int((hashlib.md5(str(time.time()).encode())).hexdigest(), 16)
    number = number % 100000000

    context = {'price' : price, 'number' : number}
    permissions = get_permissions_to_be_passed_to_template(request)
    context.update(permissions)

    return render(request, 'pharmacy/pay.html', context)

@login_required()
def add_pay_view(request):
    history_order = request.POST.get('number', 0)
    history_basket = get_basket_products(request, None)
    history_price = get_basket_price(history_basket)
    History.objects.create(user=request.user, order=history_order, price=history_price, status='Order in execution', basket=history_basket)
    response = render(request, 'pharmacy/index.html', get_permissions_to_be_passed_to_template(request))
    response.delete_cookie('basket_products')
    return response

@login_required()
def sale_view(request):
    products = Product.objects.all()
    for product in products:
        product.discount_price = float((100 - int(product.discount)) / 100.0 * float(product.price))

    context = {'all_products': products}
    permissions = get_permissions_to_be_passed_to_template(request)
    context.update(permissions)

    return render(request, 'pharmacy/sale.html', context)

@login_required()
def history_view(request):
    history = History.objects.filter(user=request.user, status='Done')
    for entry in history:
        entry.basket = ast.literal_eval(entry.basket)

    context = {'history' : history}
    permissions = get_permissions_to_be_passed_to_template(request)
    context.update(permissions)

    return render(request, 'pharmacy/history.html', context)


@login_required()
def history_execution_view(request):
    history = History.objects.filter(user=request.user, status='Order in execution')
    for entry in history:
        entry.basket = ast.literal_eval(entry.basket)

    context = {'history' : history}
    permissions = get_permissions_to_be_passed_to_template(request)
    context.update(permissions)

    return render(request, 'pharmacy/history.html', context)


@login_required()
def history_status_view(request):
    history = History.objects.filter(status='Order in execution')
    for entry in history:
        entry.basket = ast.literal_eval(entry.basket)

    context = {'history' : history}
    permissions = get_permissions_to_be_passed_to_template(request)
    context.update(permissions)

    return render(request, 'pharmacy/history_status.html', context)


@login_required()
def history_status_change_view(request):
    History.objects.filter(order=request.POST.get('order', 0)).update(status='Done')
    history = History.objects.filter(status='Order in execution')
    for entry in history:
        entry.basket = ast.literal_eval(entry.basket)

    context = {'history' : history, 'message' : 'Status updated'}
    permissions = get_permissions_to_be_passed_to_template(request)
    context.update(permissions)

    return render(request, 'pharmacy/history_status.html', context)

class CreateProduct(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    permission_required = 'pharmacy.add_product'
    raise_exception = True
    model = Product

Apteka/pharmacy/templates/pharmacy/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Pharmacy{% endblock %}</title>
    {% load staticfiles %}
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'pharmacy/style.css'%}"/>

</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{%url 'pharmacy:index' %}">PHARMACY</a>
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{%url 'pharmacy:products'%}">
                        <span class="glyphicon glyphicon-barcode" aria-hidden="true"></span>
                        &nbsp;
                        All products
                    </a>
                </li>
                <li class="">
                      <a href="{%url 'pharmacy:sale'%}">
                        <span class="glyphicon glyphicon-piggy-bank" aria-hidden="true"></span>
                        &nbsp;
                        Promotions
                    </a>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="query" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                {% if has_add_product_permission %}
                <li class="">
                      <a href="{% url 'pharmacy:add_product' %}">
                        <span class="glyphicon glyphicon glyphicon-plus" aria-hidden="true"></span>
                        &nbsp;
                        Add product
                    </a>
                </li>
                {% endif %}
                {% if has_add_basket_permission and has_change_basket_permission and has_delete_basket_permission %}
                <li class="">
                      <a href="{% url 'pharmacy:basket' %}">
                        <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
                        &nbsp;
                        Basket
                    </a>
                </li>
                {% endif %}
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Account&nbsp;
                            <span class="glyphicon glyphicon-user pull-right"></span>
                            <span class="glyphicon glyphicon-menu-down pull-right"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#">
                                    Account
                                    &nbsp;
                                    <span class="glyphicon glyphicon-cog"></span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'pharmacy:history' %}">
                                    Order history
                                    &nbsp;
                                    <span class="glyphicon glyphicon-stats"></span>
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'pharmacy:history_execution' %}">
                                    Order in execution
                                    &nbsp;
                                    <span class="badge">1</span>
                                </a>
                            </li>
                            {% if user.is_superuser %}
                            <li>
                                <a href="{% url 'pharmacy:history_status' %}">
                                    Orders
                                    &nbsp;
                                    <span class="glyphicon glyphicon-stats"></span>
                                </a>
                            </li>
                            {% endif %}
                            <li>
                                <a href="{% url 'pharmacy:logout' %}">
                                    Sign Out
                                    &nbsp;
                                    <span class="glyphicon glyphicon-log-out turn-off"></span>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

Apteka/pharmacy/templates/pharmacy/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Pharmacy{% endblock %}</title>
    {% load staticfiles %}
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'pharmacy/style.css'%}"/>

</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{%url 'pharmacy:index' %}">PHARMACY</a>
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                      <a href="{% url 'pharmacy:register' %}">
                        &nbsp;
                        Register
                    </a>
                </li>
                <li class="">
                      <a href="{% url 'pharmacy:sign_in' %}">
                        &nbsp;
                        Sign in
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

Apteka/pharmacy/templates/pharmacy/basket.html
{% extends 'pharmacy/base.html' %}

{% block body %}
    {%if sucess_message%}
        <h1>{{sucess_message}}</h1>
    {%endif%}

    {% if basket_products %}
        <div class="row">
        {% for basket_product in basket_products.values %}
            <div class="col-sm-4 col-lg-2">
                <div class="thumbnail">
                    <a href="{% url 'pharmacy:product_detail' basket_product.id %}" >
                        {% if basket_product.url %}
                            <img src="{{ basket_product.url }}" class="img-responsive">
                        {% endif %}
                    </a>
                    <div class="caption">
                        <h4>Name: &nbsp;{{ basket_product.name }}</h4>
                        {% if basket_product.discount > 0 %}
                            <h4>Price: &nbsp;<del>{{ basket_product.price }}</del> {{ basket_product.discount_price }}</h4>
                        {% else %}
                            <h4>Price: &nbsp;{{ basket_product.discount_price }}</h4>
                        {% endif %}
                        <h4 style="display: inline;">Amount: </h4>
                        <form action="{%url 'pharmacy:add_to_basket'%}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="basket_product_op" value="minus" />
                            <button type="submit" class="btn btn-default btn-sm" name="add_to_basket" value="{{basket_product.id}}">
                                <span class="glyphicon glyphicon-minus"></span>
                            </button>
                        </form>
                        <h4 style="display: inline;">{{ basket_product.amount }}</h4>
                        <form action="{%url 'pharmacy:add_to_basket'%}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="basket_product_op" value="plus" />
                            <button type="submit" class="btn btn-default btn-sm" name="add_to_basket" value="{{basket_product.id}}">
                                <span class="glyphicon glyphicon-plus"></span>
                            </button>
                        </form>
                        <a href="{% url 'pharmacy:product_detail' basket_product.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                        {% if has_change_product_permission %}
                        <a href="{% url 'pharmacy:update_product' basket_product.id %}" class="btn btn-primary btn-sm" role="button">Edit</a>
                        {% endif %}
                        {% if has_delete_product_permission %}
                        <form action="{% url 'pharmacy:delete_product' basket_product.id %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="album_id" value="{{ album.id }}" />
                            <button type="submit" class="btn btn-primary btn-sm">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
        {% endfor %}
        </div>
        <div class="row">
            <div class="col-sm-3 col-lg-3">
                <h4>Price: {{ basket_price }}</h4>
                <form action="{%url 'pharmacy:add_to_basket'%}" method="post" style="display: inline;">
                    {% csrf_token %}
                    Coupon: <input type="text" name="basket_coupon">
                    <button type="submit" class="btn btn-default btn-sm" name="add_to_basket" value="coupon">
                        Check coupon
                    </button>
                </form>
                <br>
                <form action="{%url 'pharmacy:pay'%}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-default btn-sm" name="pay">
                        Pay
                    </button>
                </form>
            </div>
        </div>
    {% else %}
        <h3>No products to display</h3>
    {% endif %}
{% endblock %}

Apteka/pharmacy/templates/pharmacy/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{firld.errors}}</span>
        </div>
        <label class="control-label col-sm-2"> {{field.label_tag}} </label>
        <div class="col-sm-10">{{field}}</div>
    </div>
{% endfor %}

Apteka/pharmacy/templates/pharmacy/index_visitor.html
{% extends 'pharmacy/base_visitor.html' %}

{% block title %}Hello{% endblock %}

{% block body %}
    {% if error_Message %}
        <p><strong> You are not loged in </strong></p>
    {% endif %}
    WITAJ
{% endblock %}

Apteka/pharmacy/templates/pharmacy/login.html
{% extends 'pharmacy/base.html' %}

{% block body %}
    {% if error_Message %}
        <p><strong> You are not loged in </strong></p>
    {% endif %}
{% endblock %}

Apteka/pharmacy/templates/pharmacy/pay.html
{% extends 'pharmacy/base.html' %}

{% block body %}
    {% if price and number %}
        <h4>Number: {{ number }}</h4>
        <h4>Price: {{ price }} </h4>
        <form action="{%url 'pharmacy:add_pay'%}" method="post" style="display: inline;">
            {% csrf_token %}
            <input type="hidden" name="number" value="{{number}}" />
            <button type="submit" class="btn btn-default btn-sm" name="add_pay">
                Pay
            </button>
        </form>
    {% endif %}
{% endblock %}

Apteka/pharmacy/templates/pharmacy/product_detail.html
{% extends 'pharmacy/base.html' %}

{% block title %}Product{% endblock %}

{% block body %}
    {% if error_Message %}
        <p><strong> You are not loged in </strong></p>
    {% endif %}
    {% if product %}
    <div class="container-fluid songs-container">
        <div class="row">
            <div class="col-sm-4 col-md-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <a href="{% url 'pharmacy:product_detail' product.id %}">
                             {% if product.product_logo%}
                                <img src="{{ product.product_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                        <h3>Name: &nbsp;{{product.name}}</h3>
                        {% if product.discount > 0 %}
                            <h3>Price: &nbsp;<del>{{ product.price }}</del> {{ product.discount_price }}</h3>
                        {% else %}
                            <h3>Price: &nbsp;{{ product.discount_price }}</h3>
                        {% endif %}
                        {% if has_change_product_permission %}
                        <form action="" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="album_id" value="{{ album.id }}" />
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-minus"></span>
                            </button>
                        </form>
                        <h4 style="display: inline;"> {{product.amount}}</h4>
                        <form action="" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="album_id" value="{{ album.id }}" />
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-plus"></span>
                            </button>
                        </form>
                        {% endif %}
                        {% if has_add_basket_permission %}
                        <form action="{%url 'pharmacy:add_to_basket'%}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-default btn-sm" name="add_to_basket" value="{{product.id}}">Add to basket </button>
                        </form>
                        {% endif %}
                        {% if has_change_product_permission %}
                        <form action="{% url 'pharmacy:update_product' product.id %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="album_id" value="{{ album.id }}" />
                            <button type="submit" class="btn btn-default btn-sm">
                                Edit
                            </button>
                        </form>
                        {% endif %}
                        {% if has_delete_product_permission %}
                        <form action="{% url 'pharmacy:delete_product' product.id %}" method="post" style="display: inline;">
                            {% csrf_token %}
                            <input type="hidden" name="album_id" value="{{ album.id }}" />
                            <button type="submit" class="btn btn-default btn-sm">
                                <span class="glyphicon glyphicon-trash"></span>
                            </button>
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-sm-8 col-md-9">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Description:</h3>
                        {{product.description}}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

Apteka/pharmacy/templates/pharmacy/register.html
{% extends 'pharmacy/base_visitor.html' %}

{% block body %}

    {% if error_Message %}
        <p><strong> You are registered </strong></p>
    {% endif %}
{% endblock %}